name: DonationGoal
main: dev.itsmeow.donationgoal.DonationGoal
version: 1.0.0
api-version: 1.15
depend: ['SidebarAPI']
commands: 
   donationgoal:
      description: Base command for modifying donation goals
      usage: /donationgoal